//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by wordsex.rc
//
#define IDC_MYICON                      2
#define IDD_ABOUTBOX                    103
#define IDS_APP_TITLE                   103
#define ID_HELP_ABOUT                   104
#define ID_FILE_EXIT                    105
#define IDS_HELLO                       106
#define IDI_WORDSEX                     107
#define IDI_SMALL                       108
#define IDC_WORDSEX                     109
#define IDD_QUERY_DIALOG                129
#define IDD_FETCH_DIALOG                131
#define IDD_KWIC_DIALOG                 132
#define IDD_STATUS_DIALOG               133
#define IDD_STORES_DIALOG               134
#define IDD_SAVE_FOLDER_DIALOG          135
#define IDD_PHRASES_DIALOG              136
#define IDD_ADD_FOLDER_DIALOG           138
#define IDD_USE_FOLDER_DIALOG           139
#define IDD_DIALOG1                     140
#define IDC_COMBO1                      1002
#define IDC_BUTTON1                     1003
#define IDC_CHECK1                      1013
#define IDC_CHECK2                      1014
#define IDC_SPIN1                       1018
#define IDC_EDIT1                       1021
#define IDC_RADIO1                      1022
#define IDC_RADIO2                      1023
#define IDC_PROGRESS1                   1023
#define IDC_RADIO3                      1024
#define IDC_EDIT2                       1031
#define ID_NEXT                         32772
#define ID_HELP_STATUS                  32774
#define ID_BACK                         32775
#define ID_ADD_CACHE                    32776
#define ID_ADD_FILE                     32781
#define ID_FILE_SAVEFILE                32784
#define ID_HELP_STORES                  32785
#define ID_HELP_USAGE                   32786
#define ID_DELETE                       32788
#define ID_ADD_PHRASES                  32789
#define ID_ADD_DIRECTORY                32793
#define ID_FILE_SAVEALL                 32795
#define ID_ADD_WEB_PAGE                 32796
#define ID_ADD_WEB_SEARCH               32797
#define ID_ADD_LINKS                    32798
#define ID_FIND_IN_PAGE                 32800
#define ID_FIND_WORD                    32801
#define ID_HELP_EZEKIEL1                32803
#define ID_HELP_YOM_TERUAH              32804
#define ID_HELP_REVELATION              32805
#define ID_FILE_PASTE                   32806
#define ID_FILE_COPY                    32807
#define ID_HELP_FONTPLUS                32808
#define ID_HELP_FONTMINUS               32809
#define ID_HELP_COLORS                  32829
#define ID_HELP_REWRAP                  32834
#define ID_FILE_INVOKE_IE               32835
#define ID_FILE_LOAD_ENGINES            32837
#define ID_FILE_SAVE_QUERY_FORMS        32838
#define ID_JUMP_BOOKMARK                32839
#define ID_FILE_SAVE_ALL_URLS           32840
#define ID_HELP_REVNOTES                32841
#define ID_CTRL_DOWN                    32842
#define ID_CTRL_DELETE                  32843
#define ID_FILE_SAVE_VOCABULARY         32844
#define ID_HELP_EXTEND_VIEW             32847
#define IDC_STATIC                      -1

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         32848
#define _APS_NEXT_CONTROL_VALUE         1033
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
